import type { LucideIcon } from "lucide-react";
import {
  LayoutGrid,
  Box,
  Columns3,
  SeparatorHorizontal,
  Minus,
  Heading1,
  AlignLeft,
  List,
  Image,
  Video,
  Star,
  ClipboardList,
  TextCursorInput,
  AlignJustify,
  CheckSquare,
  CircleDot,
  ChevronDown,
  MousePointerClick,
  Megaphone,
  Timer,
  MessageSquareQuote,
  HelpCircle,
  CreditCard,
  LayoutList,
  ShieldCheck,
  Share2,
  Camera,
  MessageCircle,
  Play,
  Code,
  Paintbrush,
  Link2,
  Type,
} from "lucide-react";
import type { CraftBlockName } from "@/modules/page-builder/blocks";

export const BLOCK_ICONS: Record<CraftBlockName, LucideIcon> = {
  CanvasRoot: LayoutGrid,
  Section: LayoutGrid,
  Container: Box,
  Columns: Columns3,
  Spacer: SeparatorHorizontal,
  Divider: Minus,
  Heading: Heading1,
  Paragraph: AlignLeft,
  List: List,
  Image: Image,
  Video: Video,
  Icon: Star,
  LeadForm: ClipboardList,
  FormInput: TextCursorInput,
  FormTextarea: AlignJustify,
  FormCheckbox: CheckSquare,
  FormRadio: CircleDot,
  FormSelect: ChevronDown,
  SubmitButton: MousePointerClick,
  CtaButton: Megaphone,
  Countdown: Timer,
  Testimonials: MessageSquareQuote,
  Faq: HelpCircle,
  PricingTable: CreditCard,
  FeatureCards: LayoutList,
  TrustBadges: ShieldCheck,
  SocialFacebook: Share2,
  SocialInstagram: Camera,
  SocialWhatsApp: MessageCircle,
  SocialYouTube: Play,
  HtmlBlock: Code,
  CustomCss: Paintbrush,
  EmbedCode: Link2,
};

export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  Basic: LayoutGrid,
  Typography: Type,
  Media: Image,
  "Lead Generation": ClipboardList,
  Marketing: Megaphone,
  Social: Link2,
  Advanced: Code,
};
