import {
  Section,
  Container,
  Columns,
  Column,
  Spacer,
  Divider,
  CanvasRoot,
} from "@/modules/page-builder/blocks/basic";
import { Heading, Paragraph, List } from "@/modules/page-builder/blocks/typography";
import { ImageBlock, VideoBlock, IconBlock } from "@/modules/page-builder/blocks/media";
import {
  LeadForm,
  FormInput,
  FormTextarea,
  FormCheckbox,
  FormRadio,
  FormSelect,
  SubmitButton,
} from "@/modules/page-builder/blocks/lead-form";
import {
  CtaButton,
  Countdown,
  MinuteTimer,
  DayTimer,
  Testimonials,
  Faq,
  PricingTable,
  FeatureCards,
  TrustBadges,
  ProgressBar,
  MapBlock,
  CalendarBlock,
  BlogPosts,
  CategoryNavigation,
  SocialShare,
  SubscribeToMailingList,
  ImageSlider,
  PhotoGallery,
  LogoShowcase,
  Survey,
  Reviews,
  NavigationMenu,
  ImageFeature,
} from "@/modules/page-builder/blocks/marketing";
import {
  SocialFacebook,
  SocialInstagram,
  SocialWhatsApp,
  SocialYouTube,
  SocialIconsGroup,
} from "@/modules/page-builder/blocks/social";
import { HtmlBlock, CustomCss, EmbedCode } from "@/modules/page-builder/blocks/advanced";

export const craftResolver = {
  CanvasRoot,
  Section,
  Container,
  Columns,
  Column,
  Spacer,
  Divider,
  Heading,
  Paragraph,
  List,
  Image: ImageBlock,
  Video: VideoBlock,
  Icon: IconBlock,
  LeadForm,
  FormInput,
  FormTextarea,
  FormCheckbox,
  FormRadio,
  FormSelect,
  SubmitButton,
  CtaButton,
  Countdown,
  MinuteTimer,
  DayTimer,
  Testimonials,
  Faq,
  PricingTable,
  FeatureCards,
  TrustBadges,
  ProgressBar,
  MapBlock,
  CalendarBlock,
  BlogPosts,
  CategoryNavigation,
  SocialShare,
  SubscribeToMailingList,
  ImageSlider,
  PhotoGallery,
  LogoShowcase,
  Survey,
  Reviews,
  NavigationMenu,
  ImageFeature,
  SocialFacebook,
  SocialInstagram,
  SocialWhatsApp,
  SocialYouTube,
  SocialIconsGroup,
  HtmlBlock,
  CustomCss,
  EmbedCode,
};

export type CraftBlockName = keyof typeof craftResolver;

export const COMPONENT_LIBRARY: Array<{
  category: string;
  items: Array<{ name: CraftBlockName; label: string }>;
}> = [
  {
    category: "Basic",
    items: [
      { name: "Section", label: "Section" },
      { name: "Container", label: "Container" },
      { name: "Columns", label: "Row" },
      { name: "Column", label: "Column" },
      { name: "Spacer", label: "Spacer" },
      { name: "Divider", label: "Divider" },
    ],
  },
  {
    category: "Typography",
    items: [
      { name: "Heading", label: "Heading" },
      { name: "Paragraph", label: "Paragraph" },
      { name: "List", label: "List" },
    ],
  },
  {
    category: "Media",
    items: [
      { name: "Image", label: "Image" },
      { name: "Video", label: "Video" },
      { name: "Icon", label: "Icon" },
    ],
  },
  {
    category: "Lead Generation",
    items: [
      { name: "LeadForm", label: "Lead Form" },
      { name: "FormInput", label: "Input" },
      { name: "FormTextarea", label: "Textarea" },
      { name: "FormCheckbox", label: "Checkbox" },
      { name: "FormRadio", label: "Radio" },
      { name: "FormSelect", label: "Dropdown" },
      { name: "SubmitButton", label: "Submit Button" },
    ],
  },
  {
    category: "Marketing",
    items: [
      { name: "CtaButton", label: "CTA Button" },
      { name: "Countdown", label: "Countdown" },
      { name: "MinuteTimer", label: "Minute Timer" },
      { name: "DayTimer", label: "Day Timer" },
      { name: "Testimonials", label: "Testimonials" },
      { name: "Reviews", label: "Reviews" },
      { name: "Faq", label: "FAQ" },
      { name: "BlogPosts", label: "Blog Posts" },
      { name: "CategoryNavigation", label: "Category Navigation" },
      { name: "SocialShare", label: "Social Share" },
      { name: "SubscribeToMailingList", label: "Subscribe to Mailing List" },
      { name: "PricingTable", label: "Pricing Table" },
      { name: "FeatureCards", label: "Feature Cards" },
      { name: "ImageSlider", label: "Image Slider" },
      { name: "PhotoGallery", label: "Photo Gallery" },
      { name: "LogoShowcase", label: "Logo Showcase" },
      { name: "Survey", label: "Survey" },
      { name: "NavigationMenu", label: "Navigation Menu" },
      { name: "TrustBadges", label: "Trust Badges" },
      { name: "ProgressBar", label: "Progress Bar" },
      { name: "MapBlock", label: "Map" },
      { name: "CalendarBlock", label: "Calendar" },
      { name: "ImageFeature", label: "Image Feature" },
    ],
  },
  {
    category: "Social",
    items: [
      { name: "SocialFacebook", label: "Facebook" },
      { name: "SocialInstagram", label: "Instagram" },
      { name: "SocialWhatsApp", label: "WhatsApp" },
      { name: "SocialYouTube", label: "YouTube" },
      { name: "SocialIconsGroup", label: "Social Icons" },
    ],
  },
  {
    category: "Advanced",
    items: [
      { name: "HtmlBlock", label: "HTML Block" },
      { name: "CustomCss", label: "Custom CSS" },
      { name: "EmbedCode", label: "Embed Code" },
    ],
  },
];
